### ISSUE TITLE
Plugin is very slow 

### ISSUE THREAD

**Issue by ankurp** [mikach/gulp-concat-sourcemap#18]
I have 110 scss and the plugin is very slow generating sourcemap for them. Is there a way to speed it up?

**Comment by mikach** [comment]
Actually you don't need to use this plugin, it's a bit deprecated. You can try `gulp-sass`, now it also has sourceMap support https://github.com/dlmanning/gulp-sass#source-maps

**Comment by ankurp** [comment]
Actually the issue is gulp-postcss plugin. Seems like they append the css in the sourcemap and apply the transform to the map which takes a long time. I will close this issue.
