### ISSUE TITLE
Support gulp-sourcemaps

### ISSUE THREAD

**Issue by mariusGundersen** [mikach/gulp-concat-sourcemap#8]
[gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps) seems like the official way to handle sourcemaps for gulp plugins. It adds a sourcemap property to the vinyl file, so plugins can accept and produce sourcemaps in a standard way.

Unfortunately gulp-concat-sourcemap does not follow this specification. It would be great if it could detect the sourcemap property on the incoming files, and if present, attach the sourcemap to the outgoing concatenated file. This way the concatenated file can be piped to other sourcemap aware plugins, like uglify.

**Comment by mariusGundersen** [comment]
Related would be the ability to accept sourcemaps and concatenate them before sending them along with the output file

**Comment by Psvensso** [comment]
If i get their specc correct they should all be concatenated into one .map file right? 
Or should the attached .sourceMap be extracted and concatenated together with their source file? 

This just gives me some concern about load size since then the user cant choose to load individual map files. (depending on the above)

**Comment by Psvensso** [comment]
Well i guess "merging it with preexisting source maps" gives me the answer to my own question.... 
https://github.com/floridoo/vinyl-sourcemaps-apply

**Comment by Psvensso** [comment]
Reading his source made it pretty obvious whats needed.

Think this could be very usefull and pretty straight forward to support.

**Comment by mariusGundersen** [comment]
I've already started to look into it, and I'll submit a pull-request as soon as the tests show that everything is working correctly.

**Comment by Psvensso** [comment]
Nice
